In [11]:
import numpy as np
import pandas as pd
import requests
import time

In [16]:
path = "Fortune_500.csv"

tickerdf = pd.read_csv(path, encoding = "ISO-8859-1").dropna()
symbollst = list(tickerdf['Ticker Symbol'])

In [17]:
symbollst

['WMT',
 'XOM',
 'BRK.A',
 'AAPL',
 'UNH',
 'MCK',
 'CVS',
 'AMZN',
 'T',
 'GM',
 'F',
 'ABC',
 'CAH',
 'COST',
 'KR',
 'GE',
 'WBA',
 'JPM',
 'FNMA',
 'GOOGL',
 'HD',
 'BAC',
 'ESRX',
 'WFC',
 'BA',
 'PSX',
 'ANTM',
 'MSFT',
 'VLO',
 'C',
 'CMCSA',
 'IBM',
 'JNJ',
 'FMCC',
 'TGT',
 'LOW',
 'MPC',
 'PG',
 'MET',
 'UPS',
 'PEP',
 'INTC',
 'DWDP',
 'ADM',
 'AET',
 'FDX',
 'UTX',
 'PRU',
 'SYY',
 'DIS',
 'HUM',
 'PFE',
 'HPQ',
 'LMT',
 'CNC',
 'CSCO',
 'HCA',
 'ETE',
 'MS',
 'GS',
 'AAL',
 'BBY',
 'CI',
 'CHTR',
 'DAL',
 'FB',
 'HON',
 'MRK',
 'ALL',
 'TSN',
 'UAL',
 'ORCL',
 'TECD',
 'TJX',
 'AXP',
 'KO',
 'NKE',
 'ANDV',
 'INT',
 'EXC',
 'RAD',
 'MMM',
 'TWX',
 'GD',
 'COF',
 'DE',
 'INTL',
 'EPD',
 'TRV',
 'HPE',
 'PM',
 'FOXA',
 'ABBV',
 'ABT',
 'PGR',
 'ARW',
 'KHC',
 'PAGP',
 'GILD',
 'MDLZ',
 'NOC',
 'RTN',
 'M',
 'USFD',
 'USB',
 'DG',
 'IP',
 'DUK',
 'SO',
 'MAR',
 'AVT',
 'LLY',
 'AMGN',
 'MCD',
 'SBUX',
 'QCOM',
 'DLTR',
 'PBF',
 'AFL',
 'AN',
 'PAG',
 'WHR',
 'UNP',
 'LUV',
 'MAN',
 'TMO',
 'BMY',
 'LEA',
 'CMI',
 'NUE',
 'MOH',
 'FLR',
 'MO',
 'PCAR',
 'HIG',
 'KSS',
 'WDC',
 'JBL',
 'V',
 'DHR',
 'KMB',
 'ACM',
 'PNC',
 'CTL',
 'NEE',
 'PCG',
 'SNX',
 'WCG',
 'PFGC',
 'SYF',
 'KMX',
 'BK',
 'GPC',
 'EMR',
 'DVA',
 'SVU',
 'GPS',
 'GIS',
 'JWN',
 'CL',
 'AEP',
 'XPO',
 'GT',
 'OMC',
 'CDW',
 'SHW',
 'PPG',
 'TXN',
 'CHRW',
 'CTSH',
 'NWL',
 'CBS',
 'MON',
 'ARMK',
 'AMAT',
 'WM',
 'DISH',
 'ITW',
 'LNC',
 'CBRE',
 'TXT',
 'ROST',
 'PFG',
 'DHI',
 'MMC',
 'ECL',
 'L',
 'KMI',
 'VIAB',
 'PYPL',
 'CELG',
 'K',
 'LVS',
 'SWK',
 'BKNG',
 'LEN',
 'LB',
 'DTE',
 'D',
 'RGA',
 'JCP',
 'MA',
 'BLK',
 'HSIC',
 'SYK',
 'JEF',
 'VFC',
 'ADP',
 'EIX',
 'BIIB',
 'CORE',
 'BBBY',
 'OKE',
 'BBT',
 'BDX',
 'AMP',
 'FDC',
 'ED',
 'PH',
 'EL',
 'STT',
 'NFLX',
 'DFS',
 'PX',
 'CSX',
 'XEL',
 'UNM',
 'UHS',
 'SRE',
 'GPI',
 'TAP',
 'LLL',
 'BLL',
 'AZO',
 'MUSA',
 'MGM',
 'ODP',
 'HUN',
 'BAX',
 'NSC',
 'CRM',
 'LH',
 'GWW',
 'QRTEA',
 'ALV',
 'LYV',
 'LDOS',
 'GLW',
 'LAD',
 'EXPE',
 'RSG',
 'JEC',
 'SAH',
 'ALLY',
 'LKQ',
 'BWA',
 'FNF',
 'STI',
 'RS',
 'NVDA',
 'CNP',
 'EBAY',
 'EMN',
 'STLD',
 'MHK',
 'PWR',
 'AAP',
 'OMI',
 'UNFI',
 'TEN',
 'GME',
 'HRL',
 'HLT',
 'FIS',
 'PEG',
 'BSX',
 'ORLY',
 'SCHW',
 'PVH',
 'CAR',
 'CCK',
 'DKS',
 'PHM',
 'APD',
 'VRTV',
 'AGCO',
 'NWSA',
 'SPTN',
 'WLK',
 'LRCX',
 'ALK',
 'JLL',
 'AXE',
 'CPB',
 'IPG',
 'DOV',
 'ZBH',
 'DF',
 'FL',
 'ES',
 'ADS',
 'FITB',
 'DGX',
 'EME',
 'WRB',
 'WCC',
 'COTY',
 'WEC',
 'MAS',
 'LSXMA',
 'HSY',
 'PPL',
 'HII',
 'MOS',
 'SJM',
 'STZ',
 'R',
 'ADBE',
 'LPNT',
 'TSCO',
 'THO',
 'DAN',
 'WY',
 'JBHT',
 'DRI',
 'YUMC',
 'BX',
 'BERY',
 'BLDR',
 'ATVI',
 'JBLU',
 'APH',
 'AMRK',
 'SPR',
 'HRS',
 'EXPD',
 'DISCA',
 'OI',
 'SANM',
 'KEY',
 'AFG',
 'OSK',
 'COL',
 'NSIT',
 'DPS',
 'AMT',
 'RL',
 'URI',
 'CASY',
 'AVY',
 'MTZ',
 'CMS',
 'HDS',
 'RJF',
 'NCR',
 'HBI',
 'ABG',
 'CFG',
 'PKG',
 'Y',
 'DDS',
 'AIZ',
 'BEN',
 'OC',
 'MSI',
 'NVR',
 'ROK',
 'WYNN',
 'AXL',
 'ORI',
 'CC',
 'AEE',
 'AJG',
 'CE',
 'SEE',
 'UGI',
 'RLGY',
 'BURL',
 'RF',
 'SPGI',
 'MKL',
 'MTB',
 'CLX',
 'AFSI',
 'KKR',
 'ULTA',
 'YUM',
 'REGN',
 'MGLN',
 'ICE',
 'INGR',
 'WYN',
 'TOL',
 'SEB',
 'BAH',
 'FAF',
 'CINF',
 'NTRS',
 'FISV',
 'HOG',
 'PDCO',
 'ON',
 'SPG',
 'WU',
 'NTAP',
 'PII',
 'ABM',
 'CTAS']

In [13]:
lst2 = []
url = "https://www.alphavantage.co/query?function=TIME_SERIES_DAILY"
apikey="V8UXD8118Z1PW4MZ"
datatype ="json"

In [14]:
for sym in symbollst:
    time.sleep(10)    
    symbol = sym
    try:
        rs = requests.get(f"{url}&symbol={sym}&apikey={apikey}&datatype={datatype}").json()
        dts =rs['Time Series (Daily)'].keys()
        for dt in dts:
            lst =[]
            lst.append (symbol)
            lst.append (dt)
            lst.append (rs['Time Series (Daily)'][dt]['1. open'])
            lst.append (rs['Time Series (Daily)'][dt]['2. high'])
            lst.append (rs['Time Series (Daily)'][dt]['3. low'])
            lst.append (rs['Time Series (Daily)'][dt]['4. close']) 
            lst.append (rs['Time Series (Daily)'][dt]['5. volume'])  
            lst2.append(lst)
    except:
        continue
df = pd.DataFrame(lst2, columns=['symbol','date','open','high','low','close','volume'])

In [15]:
df

      symbol        date      open      high       low     close    volume
0        WMT  2018-10-26   98.8100   99.6700   98.0200   98.9400  14925551
1        WMT  2018-10-25   98.0100   99.4800   97.0000   99.1800  10737074
2        WMT  2018-10-24   97.5000   99.1700   97.2750   97.5600  10364712
3        WMT  2018-10-23   96.5000   97.9850   96.1100   97.8000   9405824
4        WMT  2018-10-22   97.3400   97.5800   96.7434   97.1400   7122857
5        WMT  2018-10-19   96.0000   97.6500   96.0000   97.1500   8950724
6        WMT  2018-10-18   96.4000   97.2450   95.7400   96.1700  11398373
7        WMT  2018-10-17   95.1800   96.6200   94.9000   96.5600   9539386
8        WMT  2018-10-16   94.7000   96.0700   94.3400   95.8100  11241700
9        WMT  2018-10-15   94.5000   94.9880   93.8200   93.8200   8305499
10       WMT  2018-10-12   94.7600   95.1700   93.6700   94.8100   8553947
11       WMT  2018-10-11   95.8100   96.2900   93.6000   93.9200   9926549
12       WMT  2018-10-10   96.6000   97.8500   95.7000   95.7600   9002831
13       WMT  2018-10-09   95.6400   97.7400   95.1900   97.0800  11598892
14       WMT  2018-10-08   93.2500   94.9300   93.0201   94.6900   5762769
15       WMT  2018-10-05   93.8600   94.1900   92.8900   93.3100   6693436
16       WMT  2018-10-04   94.0700   94.5000   93.2000   94.2100   6045259
17       WMT  2018-10-03   95.5000   95.5400   94.0400   94.0700   6327390
18       WMT  2018-10-02   93.9300   95.6100   93.8500   95.1500   7754550
19       WMT  2018-10-01   94.2900   94.6600   94.0400   94.4000   4995466
20       WMT  2018-09-28   94.2800   94.3700   93.6900   93.9100   6306274
21       WMT  2018-09-27   94.1900   94.9600   93.8200   94.1300   5363446
22       WMT  2018-09-26   95.1000   95.5850   94.5200   94.5900   5918606
23       WMT  2018-09-25   95.9900   96.5200   94.9900   95.1000   6193224
24       WMT  2018-09-24   95.4400   96.0000   94.8600   94.9200   5336981
25       WMT  2018-09-21   95.9200   96.2900   95.6300   95.9000   9530133
26       WMT  2018-09-20   95.3500   95.7900   94.9500   95.7500   5552332
27       WMT  2018-09-19   95.5700   95.8925   94.8800   95.2400   5675135
28       WMT  2018-09-18   94.4600   95.5900   94.1500   95.4300   6760152
29       WMT  2018-09-17   94.7500   95.4800   94.3733   94.8200   5329819
...      ...         ...       ...       ...       ...       ...       ...
35570   CTAS  2018-07-19  192.6000  193.9400  191.4800  193.6800    673306
35571   CTAS  2018-07-18  193.8900  194.9900  192.1700  192.5300    539580
35572   CTAS  2018-07-17  193.6600  194.5900  192.6100  194.2600    499601
35573   CTAS  2018-07-16  195.7800  196.0200  192.1700  192.5000    512063
35574   CTAS  2018-07-13  195.4300  196.2700  194.9700  195.7100    320009
35575   CTAS  2018-07-12  194.5600  195.1800  193.1000  195.0600    356478
35576   CTAS  2018-07-11  192.0700  194.3100  191.9500  193.5600    477536
35577   CTAS  2018-07-10  193.0700  194.3200  192.3900  193.2900    420455
35578   CTAS  2018-07-09  191.9100  192.9900  191.5000  192.9100    576485
35579   CTAS  2018-07-06  189.3300  191.8900  188.7005  191.2700    276370
35580   CTAS  2018-07-05  187.8300  189.6100  187.2100  189.4000    408404
35581   CTAS  2018-07-03  188.9800  189.8200  186.9500  187.0800    243985
35582   CTAS  2018-07-02  184.2400  188.8700  183.2000  188.6500    451159
35583   CTAS  2018-06-29  185.7900  188.1700  185.0400  185.0700    438344
35584   CTAS  2018-06-28  184.4800  186.2700  184.1900  185.5600    251103
35585   CTAS  2018-06-27  186.0400  187.9800  184.1600  184.3500    393927
35586   CTAS  2018-06-26  185.9500  187.4100  185.8400  186.5900    425368
35587   CTAS  2018-06-25  188.3800  188.8500  184.7000  185.5800    587027
35588   CTAS  2018-06-22  190.4400  190.9900  188.3700  188.6300    477910
35589   CTAS  2018-06-21  190.1100  190.6000  188.0100  189.4600    313722
35590   CTAS  2018-06-20  191.0200  191.3700  189.5400  190.2800    338984
35591   CTAS  2018-06-19  189.7500  190.7400  187.8600  190.5500    346960
35592   CTAS  2018-06-18  190.6300  191.4500  189.3200  191.0300    399726
35593   CTAS  2018-06-15  191.7200  191.7300  189.3100  190.5100    930667
35594   CTAS  2018-06-14  193.1000  193.1000  190.8000  191.5600    487001
35595   CTAS  2018-06-13  192.1500  194.0900  192.1500  192.3000    355380
35596   CTAS  2018-06-12  191.2400  192.7700  191.1600  192.3000    298197
35597   CTAS  2018-06-11  191.2600  191.9100  189.9700  190.5200    328808
35598   CTAS  2018-06-08  189.1800  191.5800  188.6800  191.4800    289665
35599   CTAS  2018-06-07  190.8000  191.2050  187.8200  189.0700    419629

[35600 rows x 7 columns]

In [18]:
df.to_csv("output.csv")